"""Platform contracts and factory seams for staged portability work."""

from .contracts import (
    AutostartService,
    AutostartStatus,
    FileLock,
    LockBusy,
    LockHandle,
    LockMode,
    NotificationService,
    OpenTargetService,
    PathIdentity,
    PathService,
    PlatformCapabilityUnavailable,
    PlatformName,
    PlatformServices,
    PrivateStorage,
    ProcessIdentity,
    ProcessService,
    SecretStore,
)
from .factory import (
    InvalidPlatformServicesProviderResult,
    PlatformFactoryMismatch,
    PlatformServicesUnavailable,
    create_file_lock,
    create_platform_services,
    detect_platform,
    register_platform_services,
)

__all__ = [
    "AutostartService",
    "AutostartStatus",
    "FileLock",
    "LockBusy",
    "LockHandle",
    "LockMode",
    "InvalidPlatformServicesProviderResult",
    "NotificationService",
    "OpenTargetService",
    "PathIdentity",
    "PathService",
    "PlatformCapabilityUnavailable",
    "PlatformFactoryMismatch",
    "PlatformName",
    "PlatformServices",
    "PlatformServicesUnavailable",
    "PrivateStorage",
    "ProcessIdentity",
    "ProcessService",
    "SecretStore",
    "create_file_lock",
    "create_platform_services",
    "detect_platform",
    "register_platform_services",
]
